#INSERT INTO Course (code, title, classroom) VALUES ('code001', 'Mathematics', 11);
#INSERT INTO Teacher (firstname, lastname, address_line, city, country, zip_code) VALUES ('Peter', 'The Great', '1st ave, 1', 'Seattle', 'Usa', '000001');
#set @last = @@IDENTITY;
#INSERT INTO Course (code, title, classroom, teacher_id) VALUES ('code002', 'Physics', 12, @last);
#INSERT INTO Teacher (firstname, lastname, address_line, city, country, zip_code) VALUES ('James', 'The Weak', '2st ave, 2', 'Seattle', 'Usa', '000002');
#INSERT INTO Teacher (firstname, lastname, address_line, city, country, zip_code) VALUES ('John', 'Doe', '3st ave, 3', 'Seattle', 'Usa', '000003');
#set @last = @@IDENTITY;
#INSERT INTO Course (code, title, classroom, teacher_id) VALUES ('code003', 'Java', 13, @last);
#INSERT INTO Course (code, title, classroom, teacher_id) VALUES ('code004', 'Python', 14, @last);
#INSERT INTO Teacher (firstname, lastname, address_line, city, country, zip_code) VALUES ('Maria', 'The Best', '4st ave, 4', 'Seattle', 'Usa', '00004');
#set @last = @@IDENTITY;
#INSERT INTO Course (code, title, classroom, teacher_id) VALUES ('code005', 'Psychology', 15, @last);
#INSERT INTO Student (firstname, lastname, address_line, city, country, zip_code) VALUES ('StudentA', 'LastnameA', 'Address1', 'City1', 'Country1', '000001');
#INSERT INTO Student (firstname, lastname, address_line, city, country, zip_code) VALUES ('StudentB', 'LastnameB', 'Address2', 'City2', 'Country2', '000002');
#INSERT INTO Student (firstname, lastname, address_line, city, country, zip_code) VALUES ('StudentC', 'LastnameC', 'Address3', 'City3', 'Country3', '000003');
#INSERT INTO Student (firstname, lastname, address_line, city, country, zip_code) VALUES ('StudentD', 'LastnameD', 'Address4', 'City4', 'Country4', '000004');
#INSERT INTO Student (firstname, lastname, address_line, city, country, zip_code) VALUES ('StudentE', 'LastnameE', 'Address5', 'City5', 'Country5', '000005');
#INSERT INTO Student (firstname, lastname, address_line, city, country, zip_code) VALUES ('StudentF', 'LastnameF', 'Address6', 'City6', 'Country6', '000006');
#INSERT INTO Student (firstname, lastname, address_line, city, country, zip_code) VALUES ('StudentG', 'LastnameG', 'Address7', 'City7', 'Country7', '000007');
#INSERT INTO student_course (student_id, course_id) VALUES (1, 2);
#INSERT INTO student_course (student_id, course_id) VALUES (1, 3);
#INSERT INTO student_course (student_id, course_id) VALUES (3, 3);
#INSERT INTO student_course (student_id, course_id) VALUES (4, 3);
#INSERT INTO student_course (student_id, course_id) VALUES (4, 4);
#INSERT INTO student_course (student_id, course_id) VALUES (4, 5);
#INSERT INTO student_course (student_id, course_id) VALUES (5, 3);
#INSERT INTO student_course (student_id, course_id) VALUES (5, 4);
#INSERT INTO student_course (student_id, course_id) VALUES (5, 5);
#INSERT INTO student_course (student_id, course_id) VALUES (6, 2);
#INSERT INTO student_course (student_id, course_id) VALUES (6, 5);
#INSERT INTO student_course (student_id, course_id) VALUES (7, 1);
#INSERT INTO student_course (student_id, course_id) VALUES (7, 2);
#INSERT INTO student_course (student_id, course_id) VALUES (7, 3);
#INSERT INTO student_course (student_id, course_id) VALUES (7, 4);
#INSERT INTO student_course (student_id, course_id) VALUES (7, 5);
#INSERT INTO profile (student_id, birthdate, preferencies) VALUES (1, '2012-01-12', "Tennis, football");
#INSERT INTO profile (student_id, birthdate, preferencies) VALUES (2, '2012-02-12', "Tennis, football");
#INSERT INTO profile (student_id, birthdate, preferencies) VALUES (3, '2012-03-12', "Tennis, football");
#INSERT INTO profile (student_id, birthdate, preferencies) VALUES (4, '2012-04-12', "Tennis, football");
#INSERT INTO profile (student_id, birthdate, preferencies) VALUES (5, '2012-05-12', "Tennis, football");
#INSERT INTO profile (student_id, birthdate, preferencies) VALUES (6, '2012-06-12', "Tennis, football");
#INSERT INTO profile (student_id, birthdate, preferencies) VALUES (7, '2012-07-12', "Tennis, football");
